import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="py-4 flex flex-wrap md:flex-nowrap gap-4 items-center justify-center">
        <div>
          <h1 className="glowing-text-blue my-6 text-3xl font-bold">
            Brighten up your space with a custom neon sign
          </h1>
          <h2 className="glowing-text-green my-6 text-2xl font-bold">
            Get your custom neon sign now!
          </h2>
          <Link href="/buy">
            <div className="my-4 w-fit px-8 py-4 font-bold glowing-text-orange border-2 border-orange-500 -skew-x-12">BUY NOW &rarr;</div>
          </Link>
        </div>
        <img
          alt=""
          src="https://img4.dhresource.com/webp/m/0x0/f3/albu/ry/s/20/4c27265a-e09c-45cd-93fb-cfe8e12d2f0c.jpg"
          className="w-full mt-2 glowing rounded-xl max-w-[600px]"
        />
      </section>
    </>
  );
}
